debt/MET-5237 update morphia dependency
europeana/clio pull request #15
Opened 2023-09-27 15:08 UTC by jeortizquan

2023-10-10 13:33 UTC, stzanakis requested changes

2023-10-10 13:33 UTC, stzanakis commented on pom.xml
> +		<version.metis>11-SNAPSHOT</version.metis>
Let's use metis version 11.

2023-10-13 09:01 UTC, jeortizquan commented on pom.xml
> +		<version.metis>11-SNAPSHOT</version.metis>
done.

2023-10-13 09:09 UTC, jeortizquan commented
> Could you please fix the conflicts?

done.

2023-10-16 11:31 UTC, merged